Vagrant.configure("2") do |config|
  config.vm.box = "debian/sisfenix"
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provision "shell", inline: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
  config.vm.provision "shell", inline: "systemctl restart sshd"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "devStation" do |devStation|

    devStation.vm.provider "virtualbox" do |vb|
      vb.name = "devStation"
    end

    devStation.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y man gcc strace make git
	  wget -qO /root/.vimrc https://raw.githubusercontent.com/sisfenix/dotfiles/master/vim/vimrc
	  wget -qO /root/.gitconfig https://raw.githubusercontent.com/sisfenix/dotfiles/master/git/gitconfig
    SHELL
  end
end