Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", inline: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
  config.vm.provision "shell", inline: "systemctl restart sshd"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.network "private_network", ip: "192.168.56.100"
    phpweb.vm.network "forwarded_port", guest: 80, host: 80

    phpweb.vm.provider "virtualbox" do |vb|
      vb.name = "phpweb"
    end

    phpweb.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 php php-mysql
      echo '<?php \n echo "Testando conexao  com o banco <br /> <br />"; \n $servername = "192.168.56.101"; \n $username = "phpuser"; \ $password = "pass"; \n $conn = new mysqli($servername, $username, $password); \n if ($conn->connect_error) { \n die("Conexão falhou: " . $conn->connect_error); \n }\n echo "Connetado com sucesso";\n ?>' > /var/www/html/index.php
      rm -fr /var/www/html/index.html
      systemctl restart apache2
    SHELL
  end

  config.vm.define "mysqldb" do |mysql|
    mysql.vm.network "private_network", ip: "192.168.56.101"

    mysql.vm.provider "virtualbox" do |vb|
      vb.name = "mysqldb"
    end
  
    mysql.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y mysql-server
      mysql -e "create user 'phpuser'@'%' identified by 'pass';"
      sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf
      systemctl restart mysql
    SHELL
  end
end